// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc5BvJzSKz9XpJXl1I-8YCpzg0p9VGcYA',
    appId: '1:756421822783:android:1a6cd518a7f791292b6b8a',
    messagingSenderId: '756421822783',
    projectId: 'dars66-ae91b',
    databaseURL: 'https://dars66-ae91b-default-rtdb.firebaseio.com',
    storageBucket: 'dars66-ae91b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC683lZUK1fopgpaINGtAJ9a_KyRDntCTk',
    appId: '1:756421822783:ios:f2bddd93b1d98f182b6b8a',
    messagingSenderId: '756421822783',
    projectId: 'dars66-ae91b',
    databaseURL: 'https://dars66-ae91b-default-rtdb.firebaseio.com',
    storageBucket: 'dars66-ae91b.appspot.com',
    iosBundleId: 'com.example.tadbiroemas',
  );
}
